export default {
    
	SUCCESS: "_SUCCESS",
	FAIL: "_FAIL",

    BASIC_ACTION: "BASIC_ACTION",
    BASIC_ACTION_SUCCESS: "BASIC_ACTION_SUCCESS",
    BASIC_ACTION_ERROR: "BASIC_ACTION_ERROR",

    //Login page
    LOGIN: 'LOGIN',

    FORGET_PASSWORD: 'FORGET_PASSWORD',
    
    REGISTER: 'REGISTER',

    CHANGE_LOGIN_PATH: 'CHANGE_LOGIN_PATH',

    LOGOUT: 'LOGOUT',
}